@startuml Hospital

actor Funcionario 
actor Medico #lightblue;line:blue;line.bold;text:blue
actor Enfermeiro #pink;line:red;line.bold;text:red
actor FuncionarioAdmins as Admin #lightyellow;line:yellow;line.bold;text:yellow


usecase "Cadastrar procedimento" as UC1

usecase "Cadastrar paciente" as UC2
usecase "Vincular funcionario a setor" as UC3
usecase "Cadastrar forma de pagamento/convênio" as UC4

usecase "Medicar paciente" as UC5
usecase "Cadastrar equipe médica" as UC6
usecase "Reservar sala para procedimentos" as UC7
usecase "Atualizar prontuario" as UC8


Medico --> Funcionario
Enfermeiro --> Funcionario
Admin --> Funcionario

Medico --> UC1 #line:blue;line.bold;text:blue

Admin --> UC2 #line:yellow;line.bold;text:yellow
Admin --> UC3 #line:yellow;line.bold;text:yellow
Admin --> UC4 #line:yellow;line.bold;text:yellow

Enfermeiro --> UC5 #line:red;line.bold;text:red
Enfermeiro --> UC6 #line:red;line.bold;text:red
Enfermeiro --> UC7 #line:red;line.bold;text:red
Enfermeiro --> UC8 #line:red;line.bold;text:red

@enduml